### ISSUE TITLE
Sample with Stamplay

### ISSUE THREAD

**Issue by Ridermansb** [auth0-community/auth0-emberjs2-sample#4]
Add sample using [Stamplay](https://editor.stamplay.com/register?refCode=946b096a).

Stamplay integrate with Auth0, providing a URL to authenticate with Auth0.. like this: (https://.stamplayapp.com/auth/v1/auth0/connect)

[I made a Fork](https://github.com/Ridermansb/auth0-emberjs2-sample) from this repo, and tried to create a demo using Stamplay
I just redirect login/signup to the url provided by Stamplay.
[That was what do I got](http://jmp.sh/9ATpDge) ..

**Comment by beardaway** [comment]
Hey there @Ridermansb!

Sorry for such delay in response but we're people resources constraint and sometimes cannot provide as much support to our developer community as we want. It will be great if you can share it with our developer community making a thread there:

https://community.auth0.com/

Thanks a lot for that!
